### ISSUE TITLE
TypeError: Cannot create property 'ejs' on boolean 'true'

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [SC5/serverless-jest-plugin#29]
```js
    TypeError: Cannot create property 'ejs' on boolean 'true'

      1 | const mod = require('../../dist/lambdas/query-item');
      2 | 
    > 3 | const jestPlugin = require('serverless-jest-plugin');
        |                    ^
      4 | 
```

Getting an error with `sls invoke test...`

Here is what my `serverless.yml` looks like

```yaml
plugins:
  - serverless-offline
  - serverless-jest-plugin

...

custom:
  jest:
    collectCoverage: true
    collectCoverageFrom: "src/**/*.js"
    testURL: "http://localhost:3000"
```
